"""Add on delete cascade for subject_id column in GradeSubjects table

Revision ID: 0a772cbe53e4
Revises: 70664cf42b8f
Create Date: 2022-04-20 00:03:21.601693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a772cbe53e4'
down_revision = '70664cf42b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gradesubjects_subject_id_fkey', 'gradesubjects', type_='foreignkey')
    op.create_foreign_key(None, 'gradesubjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gradesubjects', type_='foreignkey')
    op.create_foreign_key('gradesubjects_subject_id_fkey', 'gradesubjects', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
