"""empty message

Revision ID: 21698f0fae27
Revises: 8cf5470faffa
Create Date: 2023-03-06 04:58:32.966058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21698f0fae27'
down_revision = '8cf5470faffa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
