"""Add new column (numeric_value) to grade table

Revision ID: 5057a44e01e6
Revises: 134d48ff1690
Create Date: 2022-04-20 02:21:59.951607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5057a44e01e6'
down_revision = '134d48ff1690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grades', sa.Column('numeric_value', sa.SmallInteger(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grades', 'numeric_value')
    # ### end Alembic commands ###
