"""empty message

Revision ID: 6ea1d21e3eb0
Revises: cc65f60d1bb3
Create Date: 2023-02-24 06:20:54.188686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ea1d21e3eb0'
down_revision = 'cc65f60d1bb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
