"""Add registration table

Revision ID: 70664cf42b8f
Revises: d5dabeb3461c
Create Date: 2022-04-15 00:13:57.054689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70664cf42b8f'
down_revision = 'd5dabeb3461c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('regi_no', sa.String(), nullable=False),
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.SmallInteger(), nullable=False),
    sa.Column('school_year_id', sa.BigInteger(), nullable=False),
    sa.Column('old_registration_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['old_registration_id'], ['registrations.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyears.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    # ### end Alembic commands ###
