"""Create Nationality table and add nationality foreign key in student table.

Revision ID: 85cf10c882a3
Revises: 5057a44e01e6
Create Date: 2022-04-24 00:53:20.479067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85cf10c882a3'
down_revision = '5057a44e01e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nationalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('masculine_form', sa.String(), nullable=False),
    sa.Column('feminine_form', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feminine_form'),
    sa.UniqueConstraint('masculine_form')
    )
    op.add_column('students', sa.Column('nationality_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'students', 'nationalities', ['nationality_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'nationality_id')
    op.drop_table('nationalities')
    # ### end Alembic commands ###
