"""empty message

Revision ID: 8cf5470faffa
Revises: d23bbf1d064f
Create Date: 2023-03-01 04:44:07.991455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf5470faffa'
down_revision = 'd23bbf1d064f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
