"""Add columns in subject table

Revision ID: c5314479a7fe
Revises: 85cf10c882a3
Create Date: 2022-12-27 03:57:31.748889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5314479a7fe'
down_revision = '85cf10c882a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('add_to_total', sa.Boolean(), nullable=False))
    op.add_column('subjects', sa.Column('higher_score', sa.SmallInteger(), nullable=True))
    op.add_column('subjects', sa.Column('lower_score', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'lower_score')
    op.drop_column('subjects', 'higher_score')
    op.drop_column('subjects', 'add_to_total')
    # ### end Alembic commands ###
