"""empty message

Revision ID: cc65f60d1bb3
Revises: 
Create Date: 2023-02-18 05:44:58.398712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc65f60d1bb3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gradingscales',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lowest_percentage', sa.SmallInteger(), nullable=False),
    sa.Column('highest_percentage', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.CheckConstraint('lowest_percentage < highest_percentage'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lowest_percentage', 'highest_percentage', name='_grading_scale_lowest_highest_per_uc')
    )
    op.create_index(op.f('ix_gradingscales_id'), 'gradingscales', ['id'], unique=False)
    op.create_index(op.f('ix_gradingscales_name'), 'gradingscales', ['name'], unique=True)
    op.create_table('levels',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_levels_id'), 'levels', ['id'], unique=False)
    op.create_index(op.f('ix_levels_name'), 'levels', ['name'], unique=True)
    op.create_table('nationalities',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('masculine_form', sa.String(), nullable=False),
    sa.Column('feminine_form', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feminine_form'),
    sa.UniqueConstraint('masculine_form')
    )
    op.create_table('schoolyears',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schoolyears_title'), 'schoolyears', ['title'], unique=True)
    op.create_table('subjects',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('foreign_name', sa.String(), nullable=False),
    sa.Column('add_to_total', sa.Boolean(), nullable=False),
    sa.Column('higher_score', sa.SmallInteger(), nullable=True),
    sa.Column('lower_score', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_foreign_name'), 'subjects', ['foreign_name'], unique=True)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=True)
    op.create_table('grades',
    sa.Column('id', sa.SmallInteger(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('numeric_value', sa.SmallInteger(), nullable=False),
    sa.Column('level_id', sa.SmallInteger(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'level_id', name='name_level_uc')
    )
    op.create_index(op.f('ix_grades_id'), 'grades', ['id'], unique=False)
    op.create_index(op.f('ix_grades_name'), 'grades', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=False),
    sa.Column('gfather_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('gender', sa.Boolean(), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('nationality_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['nationality_id'], ['nationalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('assignedteachers',
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.SmallInteger(), nullable=False),
    sa.Column('subject_id', sa.SmallInteger(), nullable=False),
    sa.Column('school_year_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyears.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('grade_id', 'subject_id', 'school_year_id')
    )
    op.create_table('marks',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.SmallInteger(), nullable=False),
    sa.Column('subject_id', sa.SmallInteger(), nullable=False),
    sa.Column('school_year_id', sa.BigInteger(), nullable=False),
    sa.Column('semaster', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('written_test', sa.Integer(), nullable=False),
    sa.Column('oral_test', sa.Integer(), nullable=False),
    sa.Column('homeworks', sa.Integer(), nullable=False),
    sa.Column('attendance', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyears.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'grade_id', 'subject_id', 'school_year_id', 'semaster', 'month')
    )
    op.create_table('registrations',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('grade_id', sa.SmallInteger(), nullable=False),
    sa.Column('school_year_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyears.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'school_year_id')
    )
    op.create_table('subject_grades',
    sa.Column('grade_id', sa.SmallInteger(), nullable=False),
    sa.Column('subject_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.PrimaryKeyConstraint('grade_id', 'subject_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_grades')
    op.drop_table('registrations')
    op.drop_table('marks')
    op.drop_table('assignedteachers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_grades_name'), table_name='grades')
    op.drop_index(op.f('ix_grades_id'), table_name='grades')
    op.drop_table('grades')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_foreign_name'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_schoolyears_title'), table_name='schoolyears')
    op.drop_table('schoolyears')
    op.drop_table('nationalities')
    op.drop_index(op.f('ix_levels_name'), table_name='levels')
    op.drop_index(op.f('ix_levels_id'), table_name='levels')
    op.drop_table('levels')
    op.drop_index(op.f('ix_gradingscales_name'), table_name='gradingscales')
    op.drop_index(op.f('ix_gradingscales_id'), table_name='gradingscales')
    op.drop_table('gradingscales')
    # ### end Alembic commands ###
