"""empty message

Revision ID: d23bbf1d064f
Revises: 6ea1d21e3eb0
Create Date: 2023-03-01 03:47:47.823554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd23bbf1d064f'
down_revision = '6ea1d21e3eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finalmarks',
    sa.Column('student_id', sa.BigInteger(), nullable=False),
    sa.Column('subject_id', sa.SmallInteger(), nullable=False),
    sa.Column('semaster', sa.Integer(), nullable=False),
    sa.Column('school_year_id', sa.BigInteger(), nullable=False),
    sa.Column('exam', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['school_year_id'], ['schoolyears.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('student_id', 'subject_id', 'semaster', 'school_year_id'),
    # sa.CheckConstraint('semaster >= 1 AND semaster <= 2'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('finalmarks')
    # ### end Alembic commands ###
